<?php

/**
 * Page Preview Extension for Magento 2
 *
 * @author     Volodymyr Konstanchuk http://konstanchuk.com
 * @copyright  Copyright (c) 2017 The authors
 * @license    http://www.opensource.org/licenses/mit-license.html  MIT License
 */

/** @var \Konstanchuk\PagePreview\Block\Info $block */
$page = $block->getPage();
if ($page):
?>
<div class="konstanchuk-page-preview">
    <div class="page-preview-inner">
        <div class="page-preview-title">
            <?php echo $block->escapeHtml($page->getTitle()); ?>
        </div>
        <div class="page-preview-actions">
            <?php
            $adminUrl = $block->getAdminEditUrl();
            if ($adminUrl):
            ?>
                <a target="_blank" href="<?php echo $block->escapeXssInUrl($adminUrl); ?>" class="page-preview-admin">
                    <?php echo __('go to admin') ?>
                </a>
            <?php endif; ?>
            <a href="#" class="page-preview-close">x</a>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
{
    "*": {
        "Konstanchuk_PagePreview/js/script": {
            "element": ".konstanchuk-page-preview",
            "response_code": <?php echo json_encode($block->getResponseCode()); ?>,
            "random_param": <?php echo json_encode(\Konstanchuk\PagePreview\Helper\Data::RANDOM_PARAM); ?>
        }
    }
}
</script>